# Generated by Django 3.2.7 on 2021-09-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_profile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='polarsteps_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
