# Generated by Django 3.2.7 on 2021-09-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='your_name',
        ),
    ]
